#!/bin/bash
# sync the package cache with other machines.

# config
conf=/etc/pkgsync/rsyncd.conf
auth=/etc/pkgsync/auth
svtype=_rsync._tcp
rsync_opts=(-auc --info=progress2 --exclude='*' --include='*.pkg.tar.zst' --include='*.pkg.tar.xz')

if [ "$(id -u)" -ne 0 ]; then
    echo "please run ${0##*/} as root."
    exit 1
fi

# wait for other instances to finish
lock=/var/lock/pkgsync.lock
[ -f "$lock" ] && echo '[pkgsync] waiting for other instances to finish syncing...'
while [ -f "$lock" ]; do sleep 1; done
trap 'rm -f "$lock"' EXIT
mkdir -p "$(dirname "$lock")"
touch "$lock"
chmod 000 "$lock"

user=$(head -1 "$auth" | cut -d: -f1)
export RSYNC_PASSWORD=$(head -1 "$auth" | cut -d: -f2-)

avahi-browse -lprt "$svtype" | while IFS= read -r sv
do
    case $sv in
        =*IPv4*PackageSync*"\058$user\064"*) ;;
        *) continue ;;
    esac

    name=$(printf '%s\n' "$sv" | cut -d';' -f7 | tr ';' :)
    host=$(printf '%s\n' "$sv" | cut -d';' -f8-9 | tr ';' :)

    echo "[pkgsync] syncing packages with $name..."

    grep -Po '^\[\K\S+(?=])|^\s*path\s*=\s*\K\S+' "$conf" |
        while IFS= read -r name && IFS= read -r path; do
            [ ! -d "$path" ] && continue
            path=${path%/}/
            url=rsync://$user@$host/$name/
            rsync "${rsync_opts[@]}" "$url" "$path"
            rsync "${rsync_opts[@]}" "$path" "$url"
        done
done
