#!/bin/sh
# sync the package cache with other machines.

# config
auth=/etc/pkgsync/auth
svtype=_rsync._tcp
rsync_opts='-au --info=progress2'

if [ "$(id -u)" -ne 0 ]; then
    echo "please run ${0##*/} as root."
    exit 1
fi

arch=$(uname -m)
user=$(head -1 "$auth" | cut -d: -f1)
export RSYNC_PASSWORD=$(head -1 "$auth" | cut -d: -f2-)

avahi-browse -lprt "$svtype" | while IFS= read -r sv
do
    case $sv in
        =*IPv4*PackageSync*"\058$user\064"*) ;;
        *) continue ;;
    esac

    name=$(printf '%s\n' "$sv" | cut -d';' -f7 | tr ';' :)
    host=$(printf '%s\n' "$sv" | cut -d';' -f8-9 | tr ';' :)
    url() { echo "rsync://$user@$host/$1-$arch/" ;}

    echo "syncing packages with $name..."

    rsync ${rsync_opts:?} /var/cache/pacman/pkg/ "$(url official)"
    rsync ${rsync_opts:?} "$(url official)" /var/cache/pacman/pkg/

    [ ! -d /var/lib/repo/aur ] && continue
    rsync ${rsync_opts:?} /var/lib/repo/aur/ "$(url aur)"
    rsync ${rsync_opts:?} "$(url aur)" /var/lib/repo/aur/
done
